version: '3.9'

x-common_config: &common_config
  volumes:
    - &shared ./project:/project
  working_dir: /project/
  user: "1000"
  stop_signal: SIGKILL
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]

services:
  dreambooth:
    <<: *common_config
    build: 
      context: ./code/dreambooth
      dockerfile: Dockerfile
    image: neb-dreambooth
    volumes:
      - *shared
      - ./code/dreambooth/:/dreambooth/
      - ./code/common/faceops.py/:/dreambooth/faceops.py
      - ..env:/project/.env
    user: "0"

  img-gen:
    <<: *common_config
    build: 
      context: ./code/img-gen
      dockerfile: Dockerfile
    image: neb-img-gen
    volumes:
      - *shared
      - ./code/img-gen/:/img-gen/
    user: "0"


  facemorpher:
    <<: *common_config
    build: 
      context: ./code/morphing
      dockerfile: Dockerfile-facemorpher
    image: neb-facemorpher
    volumes:
      - *shared

  morph:
    <<: *common_config
    build: 
      context: ./code/morphing
      dockerfile: Dockerfile
    image: neb-morph
    volumes:
      - *shared
      - ./code/morphing/:/morphing
      - ./code/common/faceops.py/:/morphing/faceops.py    

  detect-diff:
    <<: *common_config
    build: 
      context: ./code/detect-diffusion
      dockerfile: Dockerfile
    image: neb-detect-diff
    volumes:
      - *shared
      # - ./code/detect-diff/:/detect-diff
    working_dir: /dmimagedetection

  detect-morph:
    <<: *common_config
    build: 
      context: ./code/detect-morph
      dockerfile: Dockerfile
    image: neb-morph-detect
    volumes:
      - *shared
      - ./code/detect-morph:/detect-morph
    working_dir: /SPL-MAD
    
  arcfaces:
    <<: *common_config
    build: 
      context: ./code/arcfaces
      dockerfile: Dockerfile
    image: neb-arcfaces
    volumes:
      - *shared
      - ./code/arcfaces:/arcfaces
    user: "0"

  