version: '3.9'

x-common_config: &common_config
  volumes:
    - &shared ./project:/project
  working_dir: /project/
  user: "1000"
  stop_signal: SIGKILL
  deploy:
    resources:
      reservations:
        devices:
          - driver: nvidia
            device_ids: ['1']
            capabilities: [gpu]

services:
  # docker compose build dreambooth
  # docker compose run --rm dreambooth bash
  # dreambooth:
  #   <<: *common_config
  #   build: 
  #     context: ./dreambooth
  #     dockerfile: Dockerfile
  #   image: neb-dreambooth
  #   volumes:
  #     - .env:/project/.env
  #     - *dbooth
  #   working_dir: /project

  # download:
  #   build: stable-diffusion-ui/services/download/
  #   profiles: ["download"]
  #   volumes:
  #     - *v1

  # auto1111:
  #   <<: *common_config
  #   profiles: ["auto"]
  #   build: stable-diffusion-ui/services/AUTOMATIC1111
  #   image: sd-auto:62
  #   ports:
  #     - "${WEBUI_PORT:-7860}:7860"
  #   environment:
  #     - CLI_ARGS=--allow-code --medvram --xformers --enable-insecure-extension-access --api

  # imggen:
  # # docker compose build img2img
  # # docker compose run --rm img2img bash
  #   <<: *common_config
  #   build: 
  #     context: ./img2img
  #     dockerfile: Dockerfile
  #   image: neb-img2img
  #   volumes:
  #     - .env:/project/.env
  #     - *imggen
  #   working_dir: /project



  facemorpher:
    <<: *common_config
    build: 
      context: ./code/morphing
      dockerfile: Dockerfile-facemorpher
    image: neb-facemorpher
    volumes:
      - *shared

  morph:
    <<: *common_config
    build: 
      context: ./code/morphing
      dockerfile: Dockerfile
    image: neb-morph
    volumes:
      - *shared
      - ./code/morphing/:/morphing
      - ./code/common/faceops.py/:/morphing/faceops.py

  detect-diff:
    <<: *common_config
    build: 
      context: ./code/detect-diffusion
      dockerfile: Dockerfile
    image: neb-detect-diff
    volumes:
      - *shared
      # - ./code/detect-diff/:/detect-diff
    working_dir: /dmimagedetection

  detect-morph:
    <<: *common_config
    build: 
      context: .code/detect-morph
      dockerfile: Dockerfile
    image: neb-morph-detect
    volumes:
      - *shared
      - ./code/detect-morph:/detect-morph


  # arcfaces:
  #   <<: *common_config
  #   build: 
  #     context: ./arcfaces
  #     dockerfile: Dockerfile
  #   image: neb-arcfaces
  #   volumes:
  #     - ./arcfaces:/arcfaces